language: go

go:
  - 1.10.x

before_install:
  - rm -rf $HOME/gopath/src/*
  - go get -t -v ./...

script:
  - bash <(curl -s https://raw.githubusercontent.com/vehsamrak/go-multi-package-coverage/1.0.0/test.sh)

after_success:
  - bash <(curl -s https://codecov.io/bash)
