language: go

go:
  - 1.10.x

before_install:
  # system dependencies
  - apt-get install -y --force-yes libxcursor-dev libxrandr-dev libxinerama-dev libxi-dev

  # rename package name for imports
  - mv $HOME/gopath/src/github.com/Vehsamrak $HOME/gopath/src/github.com/vehsamrak

  # downloading dependencies
  - go get -t -v ./...

script:
  - bash <(curl -s https://raw.githubusercontent.com/vehsamrak/go-multi-package-coverage/1.0.0/test.sh)

after_success:
  - bash <(curl -s https://codecov.io/bash)
